services:
  healthmon:
    image: ghcr.io/alexallah/ethereum-healthmon:latest
    command:
      - --chain=execution
      - --addr=${EL_NODE}
      - --http.addr=0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST}-health.service=${RPC_HOST}-health
      - traefik.http.routers.${RPC_HOST}-health.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}-health.rule=Host(`${RPC_HOST}.${DOMAIN}`) && Path(`/ready`)
      - traefik.http.routers.${RPC_HOST}-health.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST}-health.loadbalancer.server.port=21171
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=21171
      - metrics.network=${NETWORK}
